# Generated by Django 3.1.1 on 2020-09-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.CharField(max_length=25)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
