# Generated by Django 3.1.1 on 2020-09-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='urn',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
