# Generated by Django 3.1.1 on 2021-03-29 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('aggregator', models.CharField(max_length=50)),
                ('short_code', models.CharField(max_length=10, unique=True)),
                ('request_format', models.TextField()),
                ('response_content_type', models.CharField(default='json', max_length=10)),
                ('response_method', models.CharField(default='POST', max_length=15)),
                ('response_format', models.IntegerField(default=1)),
                ('response_structure', models.TextField()),
                ('signal_reply_string', models.CharField(max_length=15)),
                ('signal_end_string', models.CharField(max_length=10)),
                ('push_support', models.BooleanField(default=False)),
                ('push_url', models.URLField(blank=True, null=True)),
                ('auth_scheme', models.CharField(default='TOKEN', max_length=30)),
                ('trigger_word', models.CharField(default='USSD', max_length=50)),
                ('repeat_trigger', models.CharField(default=' ', max_length=20)),
                ('expire_on_inactivity_of', models.IntegerField(default=300)),
                ('last_accessed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.ussdchannel')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handler_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handler_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(default='In Progress', max_length=20)),
                ('badge', models.CharField(default='info', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_access_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handlers.handler')),
            ],
        ),
    ]
