# Generated by Django 3.1.1 on 2020-09-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handler',
            name='response_format',
        ),
    ]
