# Generated by Django 3.1.1 on 2022-05-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='short_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
