# Generated by Django 3.1.1 on 2020-11-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handler',
            name='push_url',
            field=models.URLField(null=True),
        ),
    ]
