# Generated by Django 3.1.1 on 2020-09-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handler',
            name='response_structure',
            field=models.TextField(default='{{text=responseString}}, {{action=signal}}'),
        ),
    ]
