# Generated by Django 3.1.1 on 2021-03-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdsession',
            name='repeat_trigger',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
