# Generated by Django 3.1.1 on 2021-03-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0002_ussdsession_repeat_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ussdsession',
            name='repeat_trigger',
        ),
        migrations.AddField(
            model_name='handler',
            name='repeat_trigger',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
