# Generated by Django 3.1.1 on 2020-09-26 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0002_remove_handler_response_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='handler',
            name='method',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handler',
            name='remote_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handler',
            name='use_as_external_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='handler',
            name='short_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
