# Generated by Django 3.1.1 on 2021-02-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0002_handler_push_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='handler',
            name='auth_scheme',
            field=models.CharField(default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='handler',
            name='push_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
