# Generated by Django 3.1.1 on 2022-05-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0002_auto_20220502_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussdsession',
            name='session_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
