# Generated by Django 3.1.1 on 2020-09-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0002_handler_response_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='request_format',
            field=models.TextField(default='{{text=responseString}}, {{action=signal}}'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='response_structure',
            field=models.TextField(),
        ),
    ]
