# Generated by Django 3.1.1 on 2020-09-26 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0003_auto_20200926_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handler',
            name='remote_url',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='use_as_external_service',
        ),
    ]
