# Generated by Django 3.1.1 on 2020-09-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0004_auto_20200930_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handler',
            old_name='signal_response_string',
            new_name='signal_reply_string',
        ),
    ]
