# Generated by Django 3.1.1 on 2020-09-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0004_auto_20200926_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handler',
            name='method',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='response_type',
        ),
        migrations.AddField(
            model_name='handler',
            name='response_content_type',
            field=models.CharField(default='json', max_length=10),
        ),
        migrations.AddField(
            model_name='handler',
            name='response_format',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='handler',
            name='response_method',
            field=models.CharField(default='POST', max_length=15),
        ),
    ]
