# Generated by Django 3.1.1 on 2020-09-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ussdchannel',
            name='send_url',
        ),
    ]
