# Generated by Django 3.1.1 on 2020-09-29 10:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_ussdchannel_send_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdsession',
            name='last_access_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 10, 15, 13, 468267, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
