# Generated by Django 3.1.1 on 2020-10-02 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(max_length=10)),
                ('msg_body', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('receiver', models.CharField(max_length=50)),
                ('sent_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
